name: Integration Test

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-20.04', 'windows-2019', 'macos-12']

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout hayabusa-sample-evtx repo
      uses: actions/checkout@v3
      with:
        repository: Yamato-Security/hayabusa-sample-evtx
        path: hayabusa-sample-evtx

    - name: Run2
      run: cd main && cargo run --release -- 2

    - name: Run3
      run: cd main && cargo run --release -- 3