name: Integration Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-20.04', 'windows-2019', 'macos-12']

    steps:
    - name: Echo input parameter
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout hayabusa-sample-evtx repo
      uses: actions/checkout@v3
      with:
        repository: Yamato-Security/hayabusa-sample-evtx
        path: hayabusa-sample-evtx

    - name: Run
      run: cd main && cargo run --release -- 2